<a href="https://colab.research.google.com/github/newjay608/LearnPyTorch/blob/main/00_introduction_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to PyTorch

In [2]:
import sys
import platform
import torch
import numpy as np
import pandas as pd
import sklearn as sk

In [3]:
has_gpu = torch.cuda.is_available()
has_mps = torch.backends.mps.is_built()

device = "mps" if torch.backends.mps.is_available() \
  else "gpu" if torch.cuda.is_available() else "cpu"

print(f"Python Platform: {platform.platform()}")
print(f"PyTorch Version: {torch.__version__}")
print()
print(f"Python Version {sys.version_info}")
print(f"Pandas Version {pd.__version__}")
print(f"Scikit Version {sk.__version__}")
print(f"GPU is available "if has_gpu else "GPU NOT AVIALABLE")
print(f"MPS (Apple Metal) is available "if has_gpu else "APLLE METAL NOT AVIALABLE")
print(f"Target Device {device}")

Python Platform: Linux-6.1.58+-x86_64-with-glibc2.35
PyTorch Version: 2.1.0+cu121

Python Version sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Pandas Version 1.5.3
Scikit Version 1.2.2
GPU is available 
MPS (Apple Metal) is available 
Target Device gpu


## Creating Tensors

Tensors are immutable, algebraic object that decribes a multilinear realitionship between sets of algebraic objrects in a vector space

Its a multi-dimensional array of numbers, but they are not just numbers, but they also have geometry and the object is invariant undera change of coordiantes and has compoenents that change in special, predictable way under a change of cooridnates. Change of cooridnates here means you can apply any cooridnate system the lentgh (maginidute) is invariate. The components change with each coordiante system in which the vector is placed

A simplistic example of tensor is a scalar, scalars as just a number

In [4]:
scalar = torch.tensor(7)
print(f"scalar {scalar}")
print(f"scalar item value {scalar.item()}")
print(f"scalar ndim {scalar.ndim}")
print(f"scalar shape {scalar.shape}")


scalar 7
scalar item value 7
scalar ndim 0
scalar shape torch.Size([])


In [5]:
vector = torch.tensor([7,7])
print(f"vector {vector}")
print(f"vector ndim {vector.ndim}")
print(f"vector shape {vector.shape}")

vector tensor([7, 7])
vector ndim 1
vector shape torch.Size([2])


In [6]:
MATRIX = torch.tensor([[7,8],
                       [9,10],
                       [11,3]])
print(f"vector {MATRIX}")
print(f"vector ndim {MATRIX.ndim}")
print(f"vector shape {MATRIX.shape}")
print(f"first element {MATRIX[0]}")
print(f"second element {MATRIX[1]}")

vector tensor([[ 7,  8],
        [ 9, 10],
        [11,  3]])
vector ndim 2
vector shape torch.Size([3, 2])
first element tensor([7, 8])
second element tensor([ 9, 10])


In [7]:
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
print(f"vector {TENSOR}")
print(f"vector ndim {TENSOR.ndim}")
print(f"vector shape {TENSOR.shape}")

vector tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
vector ndim 3
vector shape torch.Size([1, 3, 3])


Tensors can represent almost anything. The dimensions go outer to inner.
  
The above tensor can represent a sales number for three products in three stores
or.
first row can be days of the week and second and third rows can be stake and almond sales
  
**That means there's 1 dimension of 3 by 3.**

Name: Scalar
What is it?: a single number
num of dimensions 0
Lower or upper : Lower(a)
  

Name: Vector
What is it?: a a number with directions
num of dimensions 0
Lower or upper: Lower (y)


Name: Matrix
What is it?: a 2-demensional array of numbers
num of dimensions 2
Lower or upper: Upper (Q)


Name: Tensor
What is it? an n-dimensional array of numbers
number of dimensions: can be any number - a 0 dimension is a scalar; vector is a 1-dimensional tensor
Lower or upper: Upper(X)




### Random tensors

Why Random Tensors are important?
Random tensors (numbers) is what DNNs learn and as they learn the models adjust these random tensors to better represent the data

In [11]:
random_tensor = torch.rand(3,4)
print(random_tensor)
print(f"size {random_tensor.size()}")
print(f"ndim {random_tensor.ndim}")

tensor([[0.8091, 0.7033, 0.4669, 0.2358],
        [0.3401, 0.1988, 0.5193, 0.1521],
        [0.7329, 0.8281, 0.9428, 0.2908]])
size torch.Size([3, 4])
ndim 2


In [15]:
random_tensor = torch.rand(2, 5, 4)
print(random_tensor)
print(f"size {random_tensor.shape}")
print(f"ndim {random_tensor.ndim}")

tensor([[[0.7295, 0.6315, 0.1369, 0.5716],
         [0.7469, 0.5602, 0.3322, 0.9207],
         [0.9513, 0.0192, 0.6869, 0.0060],
         [0.9652, 0.4689, 0.8848, 0.5085],
         [0.3057, 0.6807, 0.4737, 0.7017]],

        [[0.5354, 0.4131, 0.7252, 0.3372],
         [0.3943, 0.1439, 0.9396, 0.1744],
         [0.0638, 0.6556, 0.7845, 0.2872],
         [0.1093, 0.3783, 0.3128, 0.0570],
         [0.5935, 0.7019, 0.2260, 0.8169]]])
size torch.Size([2, 5, 4])
ndim 3


In [16]:
# create a random tesnor with similar shape to an image tensor, pytorch does the
# work behind the scene to generate a tensor from an image
random_image_size_tensor = torch.rand(size=(224,224,3))
print(f"size {random_image_size_tensor.shape}")
print(f"ndim {random_image_size_tensor.ndim}")

size torch.Size([224, 224, 3])
ndim 3


### Zeros and Ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size =(1,3,3))
print(zeros)
print(f"size {zeros.shape}")
print(f"ndim {zeros.ndim}")

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
size torch.Size([1, 3, 3])
ndim 3


In [19]:
ones = torch.ones(size =(2,3,3))
print(ones)
print(f"size {ones.shape}")
print(f"ndim {ones.ndim}")

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
size torch.Size([2, 3, 3])
ndim 3


### Create a range of tensors and tensors-like

In [24]:
# torch arange  - range function is depricated

#depricated
#one_to_ten = torch.range(1,11)
#print(one_to_ten)

one_to_ten = torch.arange(1,11)
print(one_to_ten)

# step
one_to_thousand = torch.arange(1,1000, step=80)
print(one_to_thousand)

# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
print(ten_zeros)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  1,  81, 161, 241, 321, 401, 481, 561, 641, 721, 801, 881, 961])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note** : Tensor data is one of the big 3 errors in pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
#Float 32 tensor
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # what datatypes https://pytorch.org/docs/stable/tensors.html
                              device=None, # What device is the tensor is on
                              requires_grad=False) # to track gradients with this tensor or not
print(float32_tensor)

#Float 32 tensor
float32_tensor2 = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # what datatypes https://pytorch.org/docs/stable/tensors.html
                              device="cuda",
                              requires_grad=False)
print(float32_tensor2)

tensor([3., 6., 9.])
tensor([3., 6., 9.], device='cuda:0')
